# Generated by Django 4.2.7 on 2023-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Income'), (2, 'Expense')], null=True),
        ),
    ]
