# Generated by Django 4.2.7 on 2023-11-15 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_transaction_date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 16, 6, 50, 189077)),
        ),
    ]
